# Generated by Django 6.1 on 2026-09-23 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=32, unique=True, verbose_name='2t58 歌曲 id')),
                ('name', models.CharField(max_length=255, verbose_name='歌名')),
                ('singers', models.CharField(blank=True, max_length=255, verbose_name='歌手')),
                ('pulled_at', models.DateTimeField(auto_now=True, verbose_name='最近在源站见到的时间')),
            ],
            options={
                'verbose_name': '歌曲',
                'verbose_name_plural': '歌曲',
            },
        ),
        migrations.CreateModel(
            name='SearchKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, unique=True, verbose_name='关键词')),
                ('crawled_pages', models.PositiveIntegerField(default=0, verbose_name='已爬到源站第几页')),
                ('total_pages', models.PositiveIntegerField(default=0, verbose_name='源站末页页码')),
                ('total_results', models.PositiveIntegerField(default=0, verbose_name='源站报的结果总数')),
                ('crawled_at', models.DateTimeField(auto_now=True, verbose_name='最近抓取时间')),
                ('source_empty', models.BooleanField(default=False, verbose_name='源站确认查不到结果')),
                ('blocked', models.BooleanField(default=False, verbose_name='被源站屏蔽')),
                ('search_count', models.PositiveIntegerField(default=0, verbose_name='被搜次数')),
                ('last_searched_at', models.DateTimeField(blank=True, null=True, verbose_name='最近被搜时间')),
            ],
            options={
                'verbose_name': '搜索关键词',
                'verbose_name_plural': '搜索关键词',
                'indexes': [models.Index(fields=['source_empty', '-search_count'], name='idx_hot_keyword')],
            },
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_page', models.PositiveIntegerField(verbose_name='来自源站第几页')),
                ('position', models.PositiveIntegerField(verbose_name='在该页里的第几位')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='Web.searchkeyword', verbose_name='关键词')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.song', verbose_name='歌曲')),
            ],
            options={
                'verbose_name': '搜索结果',
                'verbose_name_plural': '搜索结果',
                'ordering': ['source_page', 'position', 'id'],
                'indexes': [models.Index(fields=['keyword', 'source_page'], name='idx_result_page')],
                'constraints': [models.UniqueConstraint(fields=('keyword', 'song'), name='uniq_keyword_song')],
            },
        ),
    ]
