# Generated by Django 6.1 on 2026-09-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchkeyword',
            name='last_hit_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近一次计数时间'),
        ),
        migrations.AddField(
            model_name='searchkeyword',
            name='last_hit_ip',
            field=models.CharField(blank=True, max_length=64, verbose_name='最近一次计数来自哪个 IP'),
        ),
    ]
