# Generated by Django 6.1 on 2026-09-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_searchkeyword_last_hit_at_searchkeyword_last_hit_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=32, unique=True, verbose_name='2t58 歌手 id')),
                ('name', models.CharField(max_length=255, verbose_name='歌手名')),
                ('source_pic', models.URLField(blank=True, max_length=500, verbose_name='源站封面地址')),
                ('cover', models.URLField(blank=True, max_length=500, verbose_name='图床封面外链')),
                ('pulled_at', models.DateTimeField(auto_now=True, verbose_name='最近同步时间')),
            ],
            options={
                'verbose_name': '歌手',
                'verbose_name_plural': '歌手',
            },
        ),
    ]
