# Generated by Django 6.1 on 2026-09-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_singer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=32, verbose_name='2t58 歌曲 id')),
                ('play_date', models.DateField(verbose_name='播放日期（北京时间）')),
                ('name', models.CharField(max_length=255, verbose_name='歌名')),
                ('artists', models.CharField(blank=True, max_length=255, verbose_name='歌手')),
                ('plays', models.PositiveIntegerField(default=0, verbose_name='当日听完次数')),
                ('last_played_at', models.DateTimeField(blank=True, null=True, verbose_name='最近一次听完时间')),
                ('last_hit_ip', models.CharField(blank=True, max_length=64, verbose_name='最近一次计数来自哪个 IP')),
                ('last_hit_at', models.DateTimeField(blank=True, null=True, verbose_name='最近一次计数时间')),
            ],
            options={
                'verbose_name': '歌曲播放次数',
                'verbose_name_plural': '歌曲播放次数',
                'indexes': [models.Index(fields=['play_date', '-plays'], name='idx_play_rank')],
                'constraints': [models.UniqueConstraint(fields=('sid', 'play_date'), name='uniq_song_play_day')],
            },
        ),
    ]
