# Generated by Django 6.1 on 2026-09-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_songplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='intro',
            field=models.TextField(blank=True, verbose_name='歌手简介'),
        ),
        migrations.AddField(
            model_name='singer',
            name='song_pages',
            field=models.PositiveIntegerField(default=0, verbose_name='曲目总页数'),
        ),
        migrations.AddField(
            model_name='singer',
            name='songs_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='曲目最近同步时间'),
        ),
        migrations.CreateModel(
            name='SingerSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer_sid', models.CharField(max_length=32, verbose_name='2t58 歌手 id')),
                ('page', models.PositiveIntegerField(default=1, verbose_name='源站页码')),
                ('position', models.PositiveIntegerField(verbose_name='该页内第几首')),
                ('sid', models.CharField(max_length=32, verbose_name='2t58 歌曲 id')),
                ('title', models.CharField(max_length=255, verbose_name='歌手 - 歌名')),
            ],
            options={
                'verbose_name': '歌手曲目',
                'verbose_name_plural': '歌手曲目',
                'constraints': [models.UniqueConstraint(fields=('singer_sid', 'page', 'position'), name='uniq_singer_song_pos')],
            },
        ),
    ]
