# Generated by Django 6.1 on 2026-09-26 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0005_singer_intro_singer_song_pages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UcUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uc_user_id', models.CharField(max_length=64, unique=True, verbose_name='小影 user_id')),
                ('account', models.CharField(blank=True, max_length=32, verbose_name='小影账号')),
                ('username', models.CharField(blank=True, max_length=64, verbose_name='昵称')),
                ('email', models.CharField(blank=True, max_length=255, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='手机号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='首次登录时间')),
                ('last_login_at', models.DateTimeField(auto_now=True, verbose_name='最近登录时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=32, verbose_name='2t58 歌曲 id')),
                ('title', models.CharField(max_length=255, verbose_name='歌手 - 歌名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='喜欢的时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='Web.ucuser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '喜欢的歌',
                'verbose_name_plural': '喜欢的歌',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_fav_user_time')],
                'constraints': [models.UniqueConstraint(fields=('user', 'sid'), name='uniq_user_favorite')],
            },
        ),
    ]
