# Generated by Django 6.1 on 2026-09-27 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0006_ucuser_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayedSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=32, unique=True, verbose_name='2t58 歌曲 id')),
                ('name', models.CharField(max_length=255, verbose_name='歌名')),
                ('artists', models.CharField(blank=True, max_length=255, verbose_name='歌手')),
                ('singer_url', models.CharField(blank=True, max_length=500, verbose_name='源站歌手页链接')),
                ('cover', models.URLField(blank=True, max_length=500, verbose_name='封面外链')),
                ('lyrics', models.TextField(blank=True, verbose_name='歌词')),
                ('play_url', models.URLField(blank=True, max_length=1000, verbose_name='音频直链')),
                ('play_url_at', models.DateTimeField(blank=True, null=True, verbose_name='直链获取时间')),
                ('last_played_at', models.DateTimeField(blank=True, null=True, verbose_name='最近一次开始播放时间')),
                ('plays', models.PositiveIntegerField(default=0, verbose_name='累计开始播放次数')),
                ('info_at', models.DateTimeField(blank=True, null=True, verbose_name='歌曲信息抓取时间')),
            ],
            options={
                'verbose_name': '播放过的歌',
                'verbose_name_plural': '播放过的歌',
                'indexes': [models.Index(fields=['-last_played_at'], name='idx_played_recent')],
            },
        ),
    ]
